USE [master]
GO
/****** Object:  Database [INCOMEL]    Script Date: 21/04/2022 06:15:44 p. m. ******/
CREATE DATABASE [INCOMEL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'INCOMEL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\INCOMEL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'INCOMEL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\INCOMEL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [INCOMEL] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [INCOMEL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [INCOMEL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [INCOMEL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [INCOMEL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [INCOMEL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [INCOMEL] SET ARITHABORT OFF 
GO
ALTER DATABASE [INCOMEL] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [INCOMEL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [INCOMEL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [INCOMEL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [INCOMEL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [INCOMEL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [INCOMEL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [INCOMEL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [INCOMEL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [INCOMEL] SET  ENABLE_BROKER 
GO
ALTER DATABASE [INCOMEL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [INCOMEL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [INCOMEL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [INCOMEL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [INCOMEL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [INCOMEL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [INCOMEL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [INCOMEL] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [INCOMEL] SET  MULTI_USER 
GO
ALTER DATABASE [INCOMEL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [INCOMEL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [INCOMEL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [INCOMEL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [INCOMEL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [INCOMEL] SET QUERY_STORE = OFF
GO
USE [INCOMEL]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 21/04/2022 06:15:44 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DPI] [int] NULL,
	[NOMBRE] [varchar](256) NULL,
	[HIJOS] [int] NULL,
	[SALARIO] [numeric](10, 4) NULL,
	[USUARIO] [varchar](256) NULL,
	[FECHA] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERTABLE]    Script Date: 21/04/2022 06:15:44 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERTABLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](256) NULL,
	[USUARIO] [varchar](256) NULL,
	[FECHA] [date] NULL,
	[PASS] [varchar](256) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[EMPLOYEE] ON 
GO
INSERT [dbo].[EMPLOYEE] ([ID], [DPI], [NOMBRE], [HIJOS], [SALARIO], [USUARIO], [FECHA]) VALUES (1, 1531384, N'Juan Perez', 3, CAST(7000.0000 AS Numeric(10, 4)), N'JuanPerez', CAST(N'2022-04-21' AS Date))
GO
INSERT [dbo].[EMPLOYEE] ([ID], [DPI], [NOMBRE], [HIJOS], [SALARIO], [USUARIO], [FECHA]) VALUES (2, 1531384, N'Manuel Hernandez', 1, CAST(6000.0000 AS Numeric(10, 4)), N'ManuelHernandez', CAST(N'2022-04-21' AS Date))
GO
SET IDENTITY_INSERT [dbo].[EMPLOYEE] OFF
GO
SET IDENTITY_INSERT [dbo].[USERTABLE] ON 
GO
INSERT [dbo].[USERTABLE] ([ID], [NOMBRE], [USUARIO], [FECHA], [PASS]) VALUES (2, N'Carlos', N'carlos.avalos@test.com', CAST(N'1991-01-22' AS Date), N'testpass')
GO
SET IDENTITY_INSERT [dbo].[USERTABLE] OFF
GO
USE [master]
GO
ALTER DATABASE [INCOMEL] SET  READ_WRITE 
GO
